services:
  # Staging Environment
  - type: web
    name: stock-market-app-staging
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
    healthCheckPath: /_stcore/health
    autoDeploy: false  # Manual deployment via Jenkins

  # Production Environment  
  - type: web
    name: stock-market-app-production
    env: python
    plan: starter  # Paid plan for production
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
    healthCheckPath: /_stcore/health
    autoDeploy: false  # Manual deployment via Jenkins
